module.exports = {
  verbose: true,
  collectCoverage: true,
  collectCoverageFrom: ["src/**/*.{js,jsx,ts,tsx}"],
  coverageDirectory: "./.coverage",
  coverageReporters: ["html", "json", "lcov", "text"],
  setupFilesAfterEnv: ["<rootDir>/config/jest/setupFiles.js"],
  testMatch: [
    "<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}",
    "<rootDir>/src/__tests__/**/*.{js,jsx,ts,tsx}",
    "<rootDir>/src/**/*.{spec,test}.{js,jsx,ts,tsx}",
  ],
  testEnvironment: "node",
  testURL: "http://localhost",
  transform: {
    "^.+\\.(js|jsx|mjs|cjs|ts|tsx)$": "<rootDir>/config/jest/babelTransform.js",
    // "^.+\\.(js|jsx|mjs)$": "<rootDir>/node_modules/babel-jest",
    // "^.+\\.tsx?$": "<rootDir>/node_modules/ts-jest",
    "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
    "^(?!.*\\.(js|jsx|mjs|css|json)$)":
      "<rootDir>/config/jest/fileTransform.js",
  },
  transformIgnorePatterns: [
    "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs|cjs|ts|tsx)$",
    "^.+\\.module\\.(css|sass|scss)$",
  ],
  moduleNameMapper: {
    "^react-native$": "react-native-web",
    "^src/(.*)": "<rootDir>/src/$1",
    "^@assets/(.*)": "<rootDir>/src/assets/$1",
    "^@pages/(.*)": "<rootDir>/src/pages/$1",
    "^@components/(.*)": "<rootDir>/src/shared/components/$1",
    "^@hoc/(.*)": "<rootDir>/src/shared/hoc/$1",
    "^@styles/(.*)": "<rootDir>/src/shared/styles/$1",
    "^@utils/(.*)": "<rootDir>/src/shared/utils/$1",
    "^@contexts/(.*)": "<rootDir>/src/shared/contexts/$1",
    "^@services/(.*)": "<rootDir>/src/__generated__/$1",
    "^@types/(.*)": "<rootDir>/src/types/$1",
  },
  moduleFileExtensions: [
    "web.js",
    "js",
    "web.ts",
    "ts",
    "web.tsx",
    "tsx",
    "json",
    "web.jsx",
    "jsx",
    "node",
  ],
  preset: "ts-jest",
};
